"""Command-line interface: ``agentic-rag <command>``, or ``python -m agentic_rag <command>``.

Commands:
    ingest        Build the vector index from the corpus in DATA_DIR; with --download, first
                  download the corpus sources of data/sources.toml.
    eval          Run the functional evaluation on the full graph or one node (Phase 7).
    loadtest      Send N queries at a given concurrency and report latencies (Phase 8).
    export-graph  Print or write the Mermaid diagrams of the compiled graphs (Phases 3-4).
    config        Print the effective settings as KEY=value lines.
    serve         Start the Streamlit UI; with INGEST_ON_START, first download the missing
                  corpus sources and bring the index up to date (the container's command).

Exit codes:
    0    Success.
    1    The command failed. A feature that is planned for a later phase
         (``agentic_rag.errors.PlannedFeatureError``), a missing corpus and a failed corpus
         download (``ingest``) print only their message. Any other
         exception propagates with its traceback (Python then exits with 1), including a
         plain ``NotImplementedError`` from a library and a ``ValidationError`` raised inside
         a command: those are bugs, not planned gaps or configuration errors.
    2    A usage or configuration error, printed without a traceback: invalid arguments
         (argparse, or an ``InvalidArgumentError`` raised by the command), invalid settings
         (a ``pydantic.ValidationError`` while loading them, reported by variable name), or a
         ``ConfigurationError`` (for example a ``.env`` that is not UTF-8).
    130  Interrupted.

Every handler imports its target module inside the function, so ``--help`` and ``config``
stay fast and never load torch, sentence-transformers, chromadb or streamlit.
"""

import argparse
import logging
import os
import signal
import subprocess
import sys
from collections.abc import Callable, Sequence
from pathlib import Path
from types import FrameType
from typing import Final

from pydantic import BaseModel, ValidationError

from agentic_rag import __version__
from agentic_rag.config import (
    Settings,
    configure_logging,
    describe_invalid_settings,
    get_settings,
)
from agentic_rag.errors import ConfigurationError, InvalidArgumentError, PlannedFeatureError

logger = logging.getLogger(__name__)

PROG = "agentic-rag"
"""Program name shown in usage and error messages (the console script)."""

Handler = Callable[[argparse.Namespace, Settings], int]
"""A command implementation: parsed arguments and settings in, exit code out."""

Validator = Callable[[argparse.Namespace], str | None]
"""A cross-option check: returns an error message, or None when the arguments are valid."""

UI_SCRIPT: Final = Path(__file__).resolve().parent / "ui" / "app.py"
"""The Streamlit entrypoint that ``serve`` runs."""

_REPLACE_PROCESS: Final = os.name != "nt"
"""Whether ``serve`` replaces its own process with Streamlit (``os.execv``), so that Streamlit
is the container's main process and receives its signals. On Windows ``os.execv`` would detach
Streamlit from the console, so ``serve`` runs it as a child process there instead."""

_GRAPH_TITLES = {"agent": "Main agentic workflow", "rag": "RAG subgraph"}
_GENERATED_NOTE = "<!-- Generated by `agentic-rag export-graph`; do not edit by hand. -->"


def main(argv: list[str] | None = None) -> int:
    """Run the command-line interface.

    Only the errors that the module docstring maps to exit codes are caught; every other
    exception propagates with its traceback.

    Args:
        argv: The arguments without the program name; None reads ``sys.argv[1:]``.

    Returns:
        The process exit code (see the module docstring).
    """
    parser = build_parser()
    try:
        args = parser.parse_args(argv)
        problem = args.validate(args) if args.validate is not None else None
        if problem:
            args.command_parser.error(problem)
    except SystemExit as exc:  # argparse exits for --help, --version and usage errors
        return _exit_code(exc.code)

    try:
        settings = get_settings()
    except ValidationError as exc:
        print(_format_invalid_settings(exc), file=sys.stderr)
        return 2
    except ConfigurationError as exc:
        print(f"Invalid configuration: {exc}", file=sys.stderr)
        return 2

    configure_logging(settings.log_level)
    logger.debug("Running %r with LLM_PROVIDER=%s", args.command, settings.llm_provider)
    try:
        return args.handler(args, settings)
    except PlannedFeatureError as exc:
        # Only the stubs of later phases raise this type; the message names the phase.
        print(str(exc) or f"{PROG} {args.command} is planned for a later phase", file=sys.stderr)
        return 1
    except InvalidArgumentError as exc:
        # Reported like an argparse usage error of the subcommand.
        args.command_parser.print_usage(sys.stderr)
        print(f"{args.command_parser.prog}: error: {exc}", file=sys.stderr)
        return 2
    except ConfigurationError as exc:
        print(f"Invalid configuration: {exc}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        return 130


def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser with all subcommands.

    Returns:
        The parser used by ``main()``; tests and documentation tools can inspect it.
    """
    parser = argparse.ArgumentParser(
        prog=PROG,
        description="Agentic RAG chatbot prototype: build the index, evaluate, load-test and "
        "export the graphs.",
        epilog="Settings come from environment variables and a .env file (see .env.example); "
        "'agentic-rag config' prints the effective values.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    commands = parser.add_subparsers(
        dest="command", metavar="COMMAND", required=True, title="commands"
    )

    ingest = _add_command(
        commands,
        "ingest",
        _run_ingest,
        "build the vector index from the corpus in DATA_DIR",
        validate=_check_ingest_args,
    )
    ingest.add_argument(
        "--rebuild",
        action="store_true",
        help="discard the existing index and build it from scratch",
    )
    ingest.add_argument(
        "--download",
        action="store_true",
        help="first download the corpus sources into DATA_DIR at their pinned commits; "
        "sources that are up to date are skipped (needs git and network access)",
    )
    ingest.add_argument(
        "--sources",
        type=Path,
        metavar="PATH",
        help="the source list for --download (default: data/sources.toml)",
    )

    evaluation = _add_command(
        commands,
        "eval",
        _run_eval,
        "run the functional evaluation on the full graph or on a single node",
        validate=_check_eval_args,
    )
    evaluation.add_argument(
        "--target",
        choices=("graph", "node"),
        default="graph",
        help="evaluate the full graph or a single node (default: %(default)s)",
    )
    evaluation.add_argument(
        "--node",
        metavar="NAME",
        help="the main-graph node to evaluate, e.g. analyze_request; required with --target "
        "node. Only nodes that can run from an evaluation item alone are accepted",
    )
    evaluation.add_argument(
        "--dataset",
        type=Path,
        metavar="PATH",
        help="evaluation questions in JSONL (default: data/eval/questions.jsonl)",
    )
    evaluation.add_argument(
        "--output-dir",
        type=Path,
        metavar="PATH",
        help="directory for the result files (default: data/eval/results)",
    )

    loadtest = _add_command(
        commands, "loadtest", _run_loadtest, "run the load test against the compiled graph"
    )
    loadtest.add_argument(
        "--requests",
        type=_positive_int,
        default=100,
        metavar="N",
        help="number of measured queries (default: %(default)s)",
    )
    loadtest.add_argument(
        "--concurrency",
        type=_positive_int,
        default=4,
        metavar="C",
        help="number of queries in flight at the same time (default: %(default)s)",
    )
    loadtest.add_argument(
        "--warmup",
        type=_non_negative_int,
        default=3,
        metavar="W",
        help="warm-up queries sent first and reported separately (default: %(default)s)",
    )
    loadtest.add_argument(
        "--output-dir",
        type=Path,
        metavar="PATH",
        help="directory for the result files (default: data/eval/results)",
    )

    export = _add_command(
        commands,
        "export-graph",
        _run_export_graph,
        "print or write the Mermaid diagrams of the compiled graphs",
        validate=_check_export_args,
    )
    export.add_argument(
        "--graph",
        choices=("all", "agent", "rag"),
        default="all",
        help="the main workflow (agent), the RAG subgraph (rag) or both (default: %(default)s)",
    )
    export.add_argument(
        "--format",
        choices=("markdown", "mermaid"),
        default="markdown",
        help="Markdown sections with mermaid code blocks, or the raw Mermaid text of a single "
        "graph (default: %(default)s)",
    )
    export.add_argument(
        "--output",
        type=Path,
        metavar="PATH",
        help="write to this file instead of standard output",
    )

    _add_command(commands, "config", _run_config, "print the effective settings as KEY=value lines")

    serve = _add_command(
        commands,
        "serve",
        _run_serve,
        "start the Streamlit UI; with INGEST_ON_START, first download the missing corpus "
        "sources and bring the index up to date",
    )
    serve.add_argument(
        "--address",
        metavar="HOST",
        help="the address the UI listens on, e.g. 0.0.0.0 in a container (default: "
        "Streamlit's default)",
    )
    serve.add_argument(
        "--port",
        type=_port,
        default=8501,
        metavar="PORT",
        help="the port the UI listens on (default: %(default)s)",
    )
    return parser


def _add_command(
    commands: argparse._SubParsersAction,
    name: str,
    handler: Handler,
    help_text: str,
    *,
    validate: Validator | None = None,
) -> argparse.ArgumentParser:
    """Register a subcommand together with its handler and optional cross-option check."""
    command = commands.add_parser(
        name, help=help_text, description=help_text[0].upper() + help_text[1:] + "."
    )
    command.set_defaults(handler=handler, validate=validate, command_parser=command)
    return command


def _exit_code(code: object) -> int:
    """Translate the code of a SystemExit raised by argparse into an exit code."""
    if code is None:
        return 0
    return code if isinstance(code, int) else 1


def _int_at_least(text: str, minimum: int) -> int:
    """Parse an integer option value that must be at least ``minimum``."""
    try:
        value = int(text)
    except ValueError:
        msg = f"invalid integer: {text!r}"
        raise argparse.ArgumentTypeError(msg) from None
    if value < minimum:
        msg = f"must be at least {minimum}, got {value}"
        raise argparse.ArgumentTypeError(msg)
    return value


def _positive_int(text: str) -> int:
    """Argparse type for counts that must be at least 1."""
    return _int_at_least(text, 1)


def _non_negative_int(text: str) -> int:
    """Argparse type for counts that may be 0."""
    return _int_at_least(text, 0)


def _port(text: str) -> int:
    """Argparse type for a TCP port number."""
    port = _int_at_least(text, 1)
    if port > 65535:
        msg = f"must be at most 65535, got {port}"
        raise argparse.ArgumentTypeError(msg)
    return port


def _check_ingest_args(args: argparse.Namespace) -> str | None:
    """Check the option combinations of ``ingest`` that argparse cannot express."""
    if args.sources is not None and not args.download:
        return "--sources can only be used with --download"
    if args.download:
        from agentic_rag.ingestion.sources import DEFAULT_SOURCES_FILE

        sources = args.sources or DEFAULT_SOURCES_FILE
        if not sources.is_file():
            return f"--sources: file not found: {sources}"
    return None


def _check_eval_args(args: argparse.Namespace) -> str | None:
    """Check the option combinations of ``eval`` that argparse cannot express."""
    if args.target == "node" and not args.node:
        return "--node is required with --target node"
    if args.target == "graph" and args.node:
        return "--node can only be used with --target node"
    if args.dataset is not None and not args.dataset.is_file():
        return f"--dataset: file not found: {args.dataset}"
    return None


def _check_export_args(args: argparse.Namespace) -> str | None:
    """Check the option combinations of ``export-graph`` that argparse cannot express."""
    if args.format == "mermaid" and args.graph == "all":
        return "--format mermaid writes a single diagram; choose --graph agent or --graph rag"
    return None


def _run_ingest(args: argparse.Namespace, settings: Settings) -> int:
    """Download the corpus when asked, then build the vector index.

    The download logs its progress; only the index statistics go to standard output.
    """
    if args.download:
        from agentic_rag.ingestion.download import DownloadError, download_sources
        from agentic_rag.ingestion.sources import DEFAULT_SOURCES_FILE

        try:
            download_sources(settings, sources_file=args.sources or DEFAULT_SOURCES_FILE)
        except DownloadError as exc:
            print(f"{PROG} ingest: {exc}", file=sys.stderr)
            return 1

    from agentic_rag.ingestion.index import build_index

    try:
        stats = build_index(settings, rebuild=args.rebuild)
    except FileNotFoundError as exc:  # no corpus yet; the message says how to download it
        print(f"{PROG} ingest: {exc}", file=sys.stderr)
        return 1
    _print_result(stats)
    return 0


def _run_eval(args: argparse.Namespace, settings: Settings) -> int:
    """Run the evaluation with ``agentic_rag.evaluation.runner.run_evaluation``."""
    from agentic_rag.evaluation.runner import run_evaluation

    report = run_evaluation(
        settings,
        target=args.target,
        node=args.node,
        dataset_path=args.dataset,
        output_dir=args.output_dir,
    )
    _print_result(report)
    return 0


def _run_loadtest(args: argparse.Namespace, settings: Settings) -> int:
    """Run the load test with ``agentic_rag.loadtest.runner.run_load_test``."""
    from agentic_rag.loadtest.runner import run_load_test

    report = run_load_test(
        settings,
        requests=args.requests,
        concurrency=args.concurrency,
        warmup=args.warmup,
        output_dir=args.output_dir,
    )
    _print_result(report)
    return 0


def _run_export_graph(args: argparse.Namespace, settings: Settings) -> int:
    """Draw the selected compiled graphs as Mermaid (subgraphs expanded with xray)."""
    diagrams: list[tuple[str, str]] = []
    if args.graph in ("all", "agent"):
        from agentic_rag.agent.graph import build_agent_graph

        graph = build_agent_graph(settings)
        diagrams.append(("agent", graph.get_graph(xray=True).draw_mermaid()))
    if args.graph in ("all", "rag"):
        from agentic_rag.rag.graph import build_rag_graph

        graph = build_rag_graph(settings)
        diagrams.append(("rag", graph.get_graph(xray=True).draw_mermaid()))

    text = _render_diagrams(diagrams, args.format)
    if args.output is None:
        sys.stdout.write(text)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8", newline="\n")
        print(f"Wrote {args.output}", file=sys.stderr)
    return 0


def _run_config(args: argparse.Namespace, settings: Settings) -> int:
    """Print the effective settings, one KEY=value line each."""
    for name, value in settings.as_env().items():
        print(f"{name}={value}")
    return 0


def _run_serve(args: argparse.Namespace, settings: Settings) -> int:
    """Prepare the knowledge base when INGEST_ON_START is on, then run the Streamlit UI.

    A preparation that fails for a reason the user can fix (no network access for the
    download, no corpus, an invalid source list) is logged and the UI starts anyway: it
    explains in the chat that the index is missing. Any other exception propagates.
    """
    if settings.ingest_on_start:
        _prepare_on_start(settings)
    command = [
        sys.executable,
        "-m",
        "streamlit",
        "run",
        str(UI_SCRIPT),
        f"--server.port={args.port}",
    ]
    if args.address:
        command.append(f"--server.address={args.address}")
    logger.info("Starting the UI on port %d", args.port)
    return _start(command)


def _prepare_on_start(settings: Settings) -> None:
    """Run the start-up preparation; log a failure that the user can fix instead of raising.

    While it runs, SIGTERM interrupts it like Ctrl+C. As the main process of a container
    (PID 1), the process would otherwise ignore the signal that ``docker stop`` sends, and
    be killed only after the stop timeout.
    """
    from agentic_rag.ingestion.download import DownloadError
    from agentic_rag.ingestion.prepare import prepare_knowledge_base

    previous = signal.signal(signal.SIGTERM, _interrupt)
    try:
        prepare_knowledge_base(settings)
    except (DownloadError, FileNotFoundError, ConfigurationError) as exc:
        logger.error(
            "The knowledge base could not be prepared: %s. The UI starts anyway and "
            "explains in the chat what is missing.",
            exc,
        )
    finally:
        signal.signal(signal.SIGTERM, previous)


def _interrupt(signum: int, frame: FrameType | None) -> None:
    """Signal handler that turns SIGTERM into a KeyboardInterrupt (exit code 130)."""
    raise KeyboardInterrupt


def _start(command: list[str]) -> int:
    """Run a command in place of this process, or as a child where that is not possible.

    Returns:
        The exit code of the child process; on POSIX the function does not return.
    """
    sys.stdout.flush()
    sys.stderr.flush()
    if not _REPLACE_PROCESS:
        return subprocess.call(command)
    os.execv(command[0], command)


def _render_diagrams(diagrams: Sequence[tuple[str, str]], output_format: str) -> str:
    """Format exported diagrams as Markdown sections or as the raw Mermaid text of one graph."""
    if output_format == "mermaid":
        _, mermaid = diagrams[0]
        return mermaid.rstrip() + "\n"
    sections = [_GENERATED_NOTE]
    for key, mermaid in diagrams:
        sections.append(f"## {_GRAPH_TITLES[key]}\n\n```mermaid\n{mermaid.rstrip()}\n```")
    return "\n\n".join(sections) + "\n"


def _print_result(result: object) -> None:
    """Print a command result: Pydantic models as indented JSON, anything else as text."""
    if result is None:
        return
    if isinstance(result, BaseModel):
        print(result.model_dump_json(indent=2))
    else:
        print(result)


def _format_invalid_settings(error: ValidationError) -> str:
    """Describe invalid settings as plain text, one line per environment variable."""
    lines = ["Invalid configuration (check the environment variables and the .env file):"]
    lines += [f"  {name}: {problem}" for name, problem in describe_invalid_settings(error)]
    return "\n".join(lines)
